plt.plot(wav, bri)
plt.xlabel('Wavelength(cm)')
plt.ylabel('Intensity(W/m^2)')
plt.title('First Spectra')
plt.xticks(np.arange(min(wav), max(wav), step=(max(wav)-min(wav))/10))
plt.yticks(np.arange(min(bri), max(bri), step=(max(bri)-min(bri))/10))
plt.plot(wav[max_index],bri[max_index], 'ro')
plt.annotate(f'Max: ({wav[max_index]},{bri[max_index]})', (wav[max_index],bri[max_index]), textcoords="offset points", xytext=(10,7), ha='center')
plt.grid()
plt.show()